---
# tasks file for ansible-role-docker

- block:

    - name: install dependencies
      apt:
        name: "{{ docker_dependencies }}"
        state: present
        install_recommends: false

    - name: append key
      apt_key:
        url: "{{ docker_key }}"
      when: docker_key | length

    - name: append repo
      apt_repository:
        repo: "{{ docker_repo }}"
        state: present
        update_cache: true
      when: docker_repo | length

    - name: install pkg
      apt:
        name: "{{ docker_pkg }}"
        state: present
        install_recommends: false
        force: "{{ docker_pkg_force }}"

    - name: start and enable
      service:
        name: docker
        state: started
        enabled: yes

  become: yes
  tags:
    - docker
    - install

- block:

    - name: setup daemon
      copy:
        content: "{{ docker_daemon | to_json }}"
        dest: /etc/docker/daemon.json
        owner: root
        group: root
        mode: 0644
      notify: docker restart

    - name: setup users
      user:
        name: "{{ item }}"
        groups: docker
      with_items: "{{ docker_users }}"

  become: yes
  tags:
    - docker
    - setup
